package events

import (
	"bufio"
	"errors"
	"os"
	"strings"
	"testing"

	"github.com/developmi/caddy-waf-ui/internal/crs"
)

// The fixture was recorded from Caddy 2.11.6 + coraza-caddy v2.6.1 +
// Coraza v3.8.0 + CRS 4.25.0 (the versions of liukan/caddy-with-auth)
// with an overlay generated by this UI: DetectionOnly with tuning mode and
// detection PL 2 for the first six requests, then On.
func loadFixture(t *testing.T) []*Event {
	t.Helper()
	f, err := os.Open("testdata/coraza-3.8.0-audit.jsonl")
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = f.Close() }()
	n := &Normalizer{Dict: crs.Default(), Node: "test"}
	var out []*Event
	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 64*1024), 4<<20)
	for scanner.Scan() {
		e, err := n.Normalize(scanner.Bytes())
		if err != nil {
			t.Fatal(err)
		}
		out = append(out, e)
	}
	if len(out) != 9 {
		t.Fatalf("expected 9 fixture records, got %d", len(out))
	}
	return out
}

func hitIDs(e *Event) []int {
	var ids []int
	for _, h := range e.Hits {
		ids = append(ids, h.ID)
	}
	return ids
}

func TestNormalizeDetectionOnlyDecision(t *testing.T) {
	e := loadFixture(t)[0]
	if e.Path != "/.git/config" || e.Site != "example.com" || e.Host != "example.com" || e.Method != "GET" {
		t.Fatalf("request fields: %+v", e)
	}
	if e.Action != ActionWouldBlock || e.Interrupted || e.Engine != "DetectionOnly" {
		t.Fatalf("a DetectionOnly decision must be would_block: %+v", e)
	}
	if e.BlockingPL != 1 || e.DetectionPL != 2 || e.ThrIn != 5 || !e.Tuning || e.Revision == "" || e.Mode != "DetectionOnly" {
		t.Fatalf("policy signature not decoded: %+v", e)
	}
	if e.CRS != "4.25.0" || e.RuleIDs != ",930130,949110," {
		t.Fatalf("crs/rule ids: %q %q", e.CRS, e.RuleIDs)
	}
	h := e.Hits[0]
	if h.Kind != crs.KindDetection || h.Score != 5 || h.PL != 1 || h.Var != "REQUEST_FILENAME" || h.Data != redacted || h.Severity != "CRITICAL" || h.Category != "lfi" {
		t.Fatalf("930130 hit: %+v", h)
	}
	if e.Hits[1].Kind != crs.KindDecision || e.Hits[1].Severity != "" {
		t.Fatalf("949110 hit: %+v", e.Hits[1])
	}
	if e.ScoreIn != 5 || e.ReportedIn != 5 {
		t.Fatalf("recomputed %d vs reported %d", e.ScoreIn, e.ReportedIn)
	}
	if e.TS.Year() != 2026 || e.TS.Location().String() != "UTC" {
		t.Fatalf("timestamp: %v", e.TS)
	}
}

func TestNormalizeChainContinuationsAndParanoiaLevels(t *testing.T) {
	e := loadFixture(t)[1]
	count := map[int]int{}
	for _, id := range hitIDs(e) {
		count[id]++
	}
	if count[932240] != 1 || count[942130] != 1 {
		t.Fatalf("chain continuation messages must not become hits: %v", hitIDs(e))
	}
	// Only 942100 is PL1: the blocking score equals Coraza's reported total.
	if e.ScoreIn != 5 || e.ReportedIn != 5 || e.DetectIn <= e.ScoreIn {
		t.Fatalf("scores: in=%d reported=%d detect=%d", e.ScoreIn, e.ReportedIn, e.DetectIn)
	}
	if len(e.QueryKeys) != 1 || e.QueryKeys[0] != "r" || strings.Contains(e.Path, "?") {
		t.Fatalf("query keys only, no values: %q %v", e.Path, e.QueryKeys)
	}
}

func TestNormalizeSubThresholdTuningRecord(t *testing.T) {
	e := loadFixture(t)[2]
	if e.Action != ActionDetected || e.ScoreIn != 0 || len(e.Hits) != 1 {
		t.Fatalf("sub-threshold record: %+v", e)
	}
	if h := e.Hits[0]; h.ID != 920320 || h.PL != 2 || h.Severity != "NOTICE" || h.Score != 2 {
		t.Fatalf("920320: %+v", h)
	}
}

func TestNormalizeRedactsCredentials(t *testing.T) {
	cookie := loadFixture(t)[3]
	for _, h := range cookie.Hits {
		if h.Kind == crs.KindDecision {
			continue
		}
		if !strings.HasPrefix(h.Var, "REQUEST_COOKIES:") || h.Data != redacted || h.Value != redacted {
			t.Fatalf("cookie match must be redacted: %+v", h)
		}
	}
	chat := loadFixture(t)[5]
	sawPassword, sawContent := false, false
	for _, h := range chat.Hits {
		switch h.Var {
		case "ARGS:json.password":
			sawPassword = true
			if h.Data != redacted || h.Value != redacted {
				t.Fatalf("password-like JSON key must be redacted: %+v", h)
			}
		case "ARGS:json.messages.0.content":
			sawContent = true
			if h.Data != redacted {
				t.Fatalf("ordinary content must be hidden by default: %+v", h)
			}
		}
	}
	if !sawPassword || !sawContent {
		t.Fatalf("expected both JSON keys: %+v", chat.Hits)
	}
}

func TestNormalizeMultiMatchScoresPerVariable(t *testing.T) {
	e := loadFixture(t)[4]
	if e.ScoreIn != 30 || e.ReportedIn != 30 {
		t.Fatalf("each matched variable adds its score: in=%d reported=%d", e.ScoreIn, e.ReportedIn)
	}
}

func TestNormalizeBlockedRecords(t *testing.T) {
	events := loadFixture(t)
	if e := events[6]; e.Action != ActionBlocked || !e.Interrupted || e.Mode != "On" {
		t.Fatalf("On-mode decision: %+v", e)
	}
	broken := events[7]
	if broken.Action != ActionBlocked || broken.Hits[0].ID != 200002 || broken.Hits[0].Kind != crs.KindBlocking {
		t.Fatalf("direct block: %+v", broken)
	}
	scanner := events[8]
	if scanner.Hits[0].ID != 913100 || scanner.Hits[0].Category != "reputation-scanner" || len(scanner.QueryKeys) != 1 {
		t.Fatalf("scanner: %+v", scanner)
	}
}

func TestNormalizeWithoutSignatureUsesHostMapping(t *testing.T) {
	raw := `{"transaction":{"unix_timestamp":1791242354095684000,"id":"legacy-1","client_ip":"192.0.2.9",` +
		`"server_id":"www.example.com:8443","request":{"method":"POST","uri":"/login?next=%2F"},"is_interrupted":true},` +
		`"messages":[{"actionset":"OWASP_CRS/4.25.0","data":{"id":942100,"msg":"SQL Injection Attack Detected via libinjection",` +
		`"data":"Matched Data: s&1 found within ARGS:user: x' or 1=1","severity":2,"tags":["paranoia-level/1"]}}]}`
	n := &Normalizer{Dict: crs.Default(), SiteForHost: func(host string) string {
		if host == "www.example.com" {
			return "example.com"
		}
		return ""
	}}
	e, err := n.Normalize([]byte(raw))
	if err != nil {
		t.Fatal(err)
	}
	if e.Site != "example.com" || e.Host != "www.example.com" || e.Action != ActionBlocked || e.ScoreIn != 5 {
		t.Fatalf("legacy record: %+v", e)
	}
	if _, err := n.Normalize([]byte(`{"transaction":{}}`)); err == nil {
		t.Fatal("records without a transaction id must be rejected")
	}
}

// ruleLessRecord was written by Coraza v3.8.0 for a plain 404 response:
// RelevantOnly also logs every status matched by the recommended
// SecAuditLogRelevantStatus, even when no rule matched.
const ruleLessRecord = `{"transaction":{"timestamp":"2026/10/06 05:38:37","unix_timestamp":1791290317883451000,` +
	`"id":"HbNAAieffPTUbSso","client_ip":"127.0.0.1","client_port":0,"host_ip":"","host_port":0,"server_id":"localhost",` +
	`"request":{"method":"GET","protocol":"HTTP/1.1","uri":"/notfound","http_version":"","headers":null,"body":"","files":null,"args":{},"length":0},` +
	`"producer":{"connector":"","version":"","server":"","rule_engine":"DetectionOnly","stopwatch":"1791290317883451000 665000; combined=610000, p1=211000, p2=350000, p3=29000, p4=0, p5=20000",` +
	`"rulesets":["OWASP_CRS/4.25.0"]},"highest_severity":"","is_interrupted":false}}`

func TestNormalizeSkipsRecordsWithoutRuleMatches(t *testing.T) {
	n := &Normalizer{Dict: crs.Default()}
	if _, err := n.Normalize([]byte(ruleLessRecord)); !errors.Is(err, ErrNoRuleMatch) {
		t.Fatalf("a record without rule matches is not a WAF event, got %v", err)
	}
}

func TestSplitLogdata(t *testing.T) {
	cases := []struct{ in, v, d, val string }{
		{"Matched Data: .env found within REQUEST_FILENAME: /.env", "REQUEST_FILENAME", ".env", "/.env"},
		{"Matched Data: x found within ARGS:json.a.b: y found within ARGS:z: w", "ARGS:json.a.b", "x", "y found within ARGS:z: w"},
		{"Restricted header detected: /proxy/", "", "Restricted header detected: /proxy/", ""},
		{"", "", "", ""},
	}
	for _, c := range cases {
		v, d, val := splitLogdata(c.in)
		if v != c.v || d != c.d || val != c.val {
			t.Errorf("splitLogdata(%q) = %q %q %q", c.in, v, d, val)
		}
	}
	if got := truncate(strings.Repeat("中", 100), 10); !strings.HasSuffix(got, "…") || len(got) > 13 {
		t.Fatalf("truncate must respect UTF-8: %q", got)
	}
}

func TestNormalizeAppliesIPGroupTuning(t *testing.T) {
	sig := `caddy-waf-ui;v=1;site=example.com;rev=r1;mode=DetectionOnly;bpl=1;dpl=1;in=5;out=4;tune=1`
	raw := `{"transaction":{"unix_timestamp":1791290317883451000,"id":"group-tune-1","client_ip":"203.0.113.9","server_id":"example.com",` +
		`"request":{"method":"GET","uri":"/search?q=x"},"producer":{"rule_engine":"DetectionOnly","rulesets":["OWASP_CRS/4.25.0","` + sig + `"]},"is_interrupted":false},` +
		`"messages":[` +
		`{"actionset":"` + sig + `","data":{"id":9002503,"msg":"IP group policy: outside cn tune bpl=3 dpl=3 in=10 out=4"}},` +
		`{"actionset":"` + sig + `","data":{"id":942100,"msg":"SQL Injection Attack Detected via libinjection","data":"Matched Data: s&1 found within ARGS:q: x","severity":2,"tags":["paranoia-level/1"]}},` +
		`{"actionset":"` + sig + `","data":{"id":920350,"msg":"Host header is a numeric IP address","data":"Matched Data: 1.2.3.4 found within REQUEST_HEADERS:Host: 1.2.3.4","severity":4,"tags":["paranoia-level/1"]}}]}`
	e, err := (&Normalizer{Dict: crs.Default()}).Normalize([]byte(raw))
	if err != nil {
		t.Fatal(err)
	}
	if e.BlockingPL != 3 || e.DetectionPL != 3 || e.ThrIn != 10 || e.ThrOut != 4 {
		t.Fatalf("the group's thresholds must replace the site's: %+v", e)
	}
	if e.ScoreIn != 8 || e.Action != ActionDetected {
		t.Fatalf("8 points stay below the group's threshold 10: score %d, action %s", e.ScoreIn, e.Action)
	}
	if !strings.Contains(e.Hits[0].Msg, "outside cn tune") {
		t.Fatalf("the group rule keeps its specific message: %q", e.Hits[0].Msg)
	}
}
