package ui

import (
	"fmt"
	"net/url"
	"strconv"
	"strings"

	"github.com/developmi/caddy-waf-ui/internal/analysis"
	"github.com/developmi/caddy-waf-ui/internal/crs"
	"github.com/developmi/caddy-waf-ui/internal/events"
	"github.com/developmi/caddy-waf-ui/internal/waf"
)

// ruleChip is a compact rule reference in event lists.
type ruleChip struct {
	ID   int
	Msg  string
	Kind string
	Note string
}

// eventRow is one line of the event explorer.
type eventRow struct {
	E           *events.Event
	Rules       []ruleChip
	ScoreLabel  string
	ActionLabel string
	ActionClass string
}

func actionLabel(action string) string {
	switch action {
	case events.ActionBlocked:
		return "BLOCKED"
	case events.ActionWouldBlock:
		return "WOULD BLOCK"
	default:
		return "DETECTED"
	}
}

func actionClass(action string) string {
	switch action {
	case events.ActionBlocked:
		return "badge-deny"
	case events.ActionWouldBlock:
		return "badge-would"
	default:
		return "badge-detect"
	}
}

func buildEventRows(list []*events.Event, dict *crs.Dictionary) []eventRow {
	rows := make([]eventRow, 0, len(list))
	for _, e := range list {
		row := eventRow{E: e, ActionLabel: actionLabel(e.Action), ActionClass: actionClass(e.Action)}
		_, _, in, out := e.Thresholds()
		row.ScoreLabel = fmt.Sprintf("%d / %d", e.ScoreIn, in)
		if e.ScoreOut > 0 {
			row.ScoreLabel += fmt.Sprintf(" · out %d / %d", e.ScoreOut, out)
		}
		seen := map[int]bool{}
		for _, h := range e.Hits {
			if seen[h.ID] {
				continue
			}
			seen[h.ID] = true
			chip := ruleChip{ID: h.ID, Msg: h.Msg, Kind: h.Kind}
			if r, ok := dict.Lookup(h.ID); ok {
				chip.Msg = r.Msg
				chip.Kind = r.Kind
				chip.Note, _ = crs.Note(r)
			}
			row.Rules = append(row.Rules, chip)
		}
		rows = append(rows, row)
	}
	return rows
}

// hitView explains one rule match of an event.
type hitView struct {
	events.Hit
	Rule         crs.Rule
	Known        bool
	NoteZH       string
	CategoryZH   string
	Counted      bool
	Contribution string
	Excludable   bool
}

func buildHitViews(e *events.Event, dict *crs.Dictionary) []hitView {
	bpl, _, in, out := e.Thresholds()
	views := make([]hitView, 0, len(e.Hits))
	for _, h := range e.Hits {
		v := hitView{Hit: h}
		v.Rule, v.Known = dict.Lookup(h.ID)
		if v.Known {
			v.NoteZH, v.CategoryZH = crs.Note(v.Rule)
		}
		v.Excludable = !v.Known || v.Rule.IsExcludable()
		pl := h.PL
		if pl == 0 {
			pl = 1
		}
		switch h.Kind {
		case crs.KindDetection:
			dir := "inbound"
			if h.Dir == crs.DirOutbound {
				dir = "outbound"
			}
			if pl <= bpl {
				v.Counted = true
				v.Contribution = fmt.Sprintf("+%d %s (PL%d, %s)", h.Score, dir, pl, h.Severity)
			} else {
				v.Contribution = fmt.Sprintf("logged only: PL%d is above blocking PL%d (+%d if raised)", pl, bpl, h.Score)
			}
		case crs.KindDecision:
			v.Excludable = false
			if h.Dir == crs.DirOutbound {
				v.Contribution = fmt.Sprintf("decision: outbound score %d ≥ threshold %d", e.ScoreOut, out)
			} else {
				score := e.ScoreIn
				if e.ReportedIn > 0 {
					score = e.ReportedIn
				}
				v.Contribution = fmt.Sprintf("decision: inbound score %d ≥ threshold %d", score, in)
			}
		case crs.KindBlocking:
			v.Contribution = "direct block, independent of the anomaly score"
		case crs.KindUI:
			v.Contribution = "rule generated by this UI"
		default:
			v.Contribution = "custom rule (not in the CRS dictionary)"
		}
		views = append(views, v)
	}
	return views
}

// ruleView is the rule detail page model.
type ruleView struct {
	Rule       crs.Rule
	Known      bool
	NoteZH     string
	CategoryZH string
	Summary    *analysis.RuleSummary
}

func buildRuleView(id int, dict *crs.Dictionary, report *analysis.Report) ruleView {
	v := ruleView{}
	v.Rule, v.Known = dict.Lookup(id)
	if v.Known {
		v.NoteZH, v.CategoryZH = crs.Note(v.Rule)
	}
	if report != nil {
		for i := range report.Rules {
			if report.Rules[i].ID == id {
				v.Summary = &report.Rules[i]
				break
			}
		}
	}
	return v
}

// exclusionURL builds the exclusions page link prefilled with a candidate.
func exclusionURL(site string, rule int, path, pathMatch, param string) string {
	q := url.Values{}
	q.Set("tab", "exclusions")
	q.Set("domain", site)
	q.Set("rule", strconv.Itoa(rule))
	if path != "" {
		q.Set("path", path)
		q.Set("path_match", pathMatch)
	}
	if param != "" {
		q.Set("param", param)
	}
	return "/?" + q.Encode()
}

// paramFromVar returns the ARGS key of a matched variable, or "" when the
// variable cannot scope an exclusion (headers, cookies, file names).
func paramFromVar(variable string) string {
	for _, prefix := range []string{"ARGS:", "ARGS_GET:", "ARGS_POST:"} {
		if key, ok := strings.CutPrefix(variable, prefix); ok {
			if waf.ValidateParam(key) == nil {
				return key
			}
			return ""
		}
	}
	return ""
}

// eventsURL builds an event explorer link with filters.
func eventsURL(values map[string]string) string {
	q := url.Values{}
	q.Set("tab", "events")
	for k, v := range values {
		if v != "" {
			q.Set(k, v)
		}
	}
	return "/?" + q.Encode()
}
