package domain

import (
	"fmt"
	"strings"
	"time"
)

// Shared contract for the overlay header (finding J5-4): the
// "# domain: | mode: | updated:" format used to live as literals in the 3
// writers (waf, exclusions, ip-rules) and was re-parsed by hand in the
// scanner. Header/ParseHeader are the only place that knows the format; the
// writers generate and the scanner consumes, with an exact round-trip (see
// overlay_test.go).
//
// The header is an on-disk file contract: its shape MUST NOT change
// (backwards compat with existing overlays).

// headerPrefix is the prefix that identifies the header inside an overlay.
const headerPrefix = "# domain:"

// OverlayHeader describes the fields carried by an overlay header.
// Mode keeps the RAW value ("" if the header carries no mode): interpreting
// the mode's validity is up to the consumer (the scanner marks the site as
// degraded on an unknown mode, W1).
type OverlayHeader struct {
	Domain     string
	Mode       WAFMode
	Updated    time.Time
	HasMode    bool
	HasUpdated bool
	// UpdatedRaw is the raw "updated" value (so the consumer can surface the
	// real value when the timestamp does not parse).
	UpdatedRaw string
}

// Header builds the header line of an overlay. With a non-empty mode it
// emits the 3-segment format (waf); without a mode, the 2-segment one
// (exclusions and ip-rules). The timestamp is always normalized to UTC
// RFC3339: that is the format ParseHeader parses and the UI displays.
func Header(domain string, mode WAFMode, updated time.Time) string {
	ts := updated.UTC().Format(time.RFC3339)
	if mode == "" {
		return fmt.Sprintf("%s %s | updated: %s", headerPrefix, domain, ts)
	}
	return fmt.Sprintf("%s %s | mode: %s | updated: %s", headerPrefix, domain, mode, ts)
}

// ParseHeader extracts the fields of an overlay header line generated by
// Header(). It is tolerant of spacing and key capitalization (same behavior
// as the scanner's historical parser): unknown segments are ignored, an
// unparseable "updated" is flagged with HasUpdated=false, and an empty domain
// is an error.
func ParseHeader(line string) (OverlayHeader, error) {
	line = strings.TrimSpace(line)
	if !strings.HasPrefix(line, headerPrefix) {
		return OverlayHeader{}, fmt.Errorf("header %q not found", headerPrefix)
	}

	// First segment: the domain. Following segments: key: value pairs.
	rest := strings.TrimSpace(strings.TrimPrefix(line, headerPrefix))
	domainPart, remaining, _ := strings.Cut(rest, "|")

	h := OverlayHeader{Domain: strings.TrimSpace(domainPart)}
	if h.Domain == "" {
		return OverlayHeader{}, fmt.Errorf("header without domain")
	}

	for _, part := range strings.Split(remaining, "|") {
		key, value, ok := strings.Cut(strings.TrimSpace(part), ":")
		if !ok {
			continue
		}
		switch strings.ToLower(strings.TrimSpace(key)) {
		case "mode":
			h.Mode = WAFMode(strings.TrimSpace(value))
			h.HasMode = true
		case "updated":
			raw := strings.TrimSpace(value)
			h.UpdatedRaw = raw
			if ts, err := time.Parse(time.RFC3339, raw); err == nil {
				h.Updated = ts
				h.HasUpdated = true
			}
		}
	}

	return h, nil
}

// HeaderDomain returns the domain of the first header line of an overlay, or
// "" when the content has no valid header.
func HeaderDomain(content []byte) string {
	for _, line := range strings.Split(string(content), "\n") {
		if trimmed := strings.TrimSpace(line); strings.HasPrefix(trimmed, headerPrefix) {
			h, err := ParseHeader(trimmed)
			if err != nil {
				return ""
			}
			return h.Domain
		}
	}
	return ""
}
